version: "3"
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - postgres
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
        - "8000:9000"
    expose:
        - "9000"
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
        - app
    networks:
      - app-network


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
        POSTGRES_DB: lottery_db
        POSTGRES_USER: lottery
        POSTGRES_PASSWORD: 123456
    ports:
         - "5432:5432"
    volumes:
        - local_pgdata:/var/lib/postgresql/data
    networks:
        - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: jahan@gmail.com
        PGADMIN_DEFAULT_PASSWORD: 123456
        PGADMIN_LISTEN_PORT: 80
        PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    ports:
         - "8080:80"
    networks:
              - app-network
    volumes:
        - pgadmin-data:/var/lib/pgadmin
    depends_on:
        - postgres

#Docker Networks
networks:
  app-network:
    driver: bridge
volumes:
    local_pgdata:
    pgadmin-data:
